id: ironcomponents_setup
learningObjectives:
  - Install the styled-components library
hints:
  - Add the package to the frontend folder trough the docker terminal using yarn add styled-components
  - Make sure you are in the frontend folder
  - Don't forget to restart the container
startFlow:
  do:
    - actionId: github_commit_file
      params:
        file: ${theme.js}
        path: './frontend/src/styles'
        message: 'Adds theme file'
    - actionId: github_commit_file
      params:
        file: ${GlobalStyle.js}
        path: './frontend/src/styles'
        message: 'Adds GlobalStyle file'
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "We need to make our components tough as iron. It would be a good idea to start using the styled-components library and have some CSS on JS action. We'll start by installing the package in the application and doing the initial setup."
            delay: 2000
          - text: "Here's the [documentation](https://styled-components.com/docs). For now you just need to do a couple of things:"
            delay: 2000
          - text: 'First of all, run **git pull origin main** to have the latest changes.'
            delay: 2000
          - text: ':instruction[ Then, create a new branch and install the styled-components package trough the **docker frontend image** using **yarn add**. You can use the integrated terminal on Docker Desktop.]'
            delay: 2000
          - text: 'It might also be a good idea to restart your docker container afterwards. **Open a PR** so we can review the changes.'
            delay: 2000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_is_file_modified
                params:
                  defaultResult: true
                paramsFramework:
                  node:
                    fileName: frontend/package.json
                onFalseParams:
                  pr_reject_message: 'Did you add the styled-components package?  Make sure to add it trough the docker terminal using yarn add.'
                  pr_reject_message_name: 'missing_dependency'
            then:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
            else:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: '${pr_reject_message}'
                        delay: 1000
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: '${pr_reject_message}'
                    messageName: '${pr_reject_message_name}'
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'I am seeing an error message from one of the tests in GitHub actions, please check it out and fix it.'
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: 'Looks like there are some errors. Can you try to fix it?'
        github_pr_merged:
          do:
            - actionId: finish_step
