id: ironcomponents_theme
learningObjectives:
  - Setting up the ThemeProvider
hints:
  - Make sure that you are wrapping the application with the ThemeProvider
  - Don't forget to import both the ThemeProvider and the theme variable into index.js
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Now that we have the library installed, let's add some things we'll need to use it in the future. Here you have a file that includes a theme object. These are just a couple of styles to be used in the future. "
            delay: 3500
          - text: "With these styles we can now setup the ThemeProvider. You can see how [here](https://styled-components.com/docs/advanced#theming). The only difference is that we want to do this on **index.js** and using the theme object we created. Let me know once you've finished!"
            delay: 3500
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
        - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
          - actionId: bot_message
            params:
              person: keen
              messages:
                - text: "Awesome! We'll use this theme in the future, but for now let's finish the setup before we start thinkering."
          - actionId: finish_step
