id: ironcomponents_global
learningObjectives:
  - Setting up the GlobalStyles component
hints:
  - Make sure the GlobalStyle is imported (from the correct file) into index.js
  - Check if you placed the GlobalStyle correctly in index.js (inside ThemeProvider)
  - GlobalStyle should be a self-closing tag and without any props
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: 'Besides the theme we can also use **global styles**. These will be useful if we want to define some constant properties throughout our application, like default spacing or colors.'
            delay: 2000
          - text: "For this we need the **GlobalStyle.js** file that I added inside the src/styled folder. This file contains the GlobalStyle component. It's already created but you can check the [docs](https://styled-components.com/docs/api#createglobalstyle) to see how it works."
            delay: 2000
          - text: 'If you look into the file you can see that we just setup the default values for the body tag that we already had in our css.'
            delay: 3500
          - text: ':instruction[Import the GlobalStyle (from the file added) into **index.js** and place it in your React tree, **inside the ThemeProvider component**.]'
            delay: 3500
          - text: "**Open up a PR** once it's done."
            delay: 1500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_is_file_modified
                params:
                  defaultResult: true
                paramsFramework:
                  node:
                    fileName: frontend/src/index.js
                onFalseParams:
                  pr_reject_message: 'Did you add the GlobalStyle in index.js?'
                  pr_reject_message_name: 'missing_setup_global'
            then:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
            else:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: '${pr_reject_message}'
                        delay: 1000
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: '${pr_reject_message}'
                    messageName: '${pr_reject_message_name}'
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'I am seeing an error message from one of the tests in GitHub actions, please check it out and fix it.'
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: 'Looks like there are some errors. Can you try to fix it?'
        github_pr_merged:
          do:
            - actionId: finish_step
