id: iron_components_setup
learningObjectives:
  - Setting up the styled-components library
hints:
  - Make sure that you are wrapping the application with the ThemeProvider
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Looks like we need to update the way we're doing our CSS for the application. It would be a good idea to start using the styled-components library and have some CSS on JS action. Install the package in the application and try to do the initial setup."
            delay: 2000
          - text: "Here's the [documentation](https://styled-components.com/docs). For now just set up the Theme Provider with a theme variable on index.js so that later we can use some styles everywhere troughout the application. For now that theme variable can be an empty object."
            delay: 3500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    if:
    conditions:
      - conditionId: github_is_file_modified
        params:
          defaultResult: true
        paramsFramework:
          node:
            fileName: frontend/package.json
        onFalseParams:
          pr_reject_message: 'Did you add the styled-components package to the dependency list? Make sure to add it to the **frontend** project.'
          pr_reject_message_name: 'missing_dependency'
        then:
          do:
            - actionId: bot_message
          params:
          person: keen
          messages:
            - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
            - actionId: finish_step
    else:
      do:
        - actionId: bot_message
          params:
            person: keen
            messages:
              - text: '${pr_reject_message}'
                delay: 1000
        - actionId: github_pr_reject
          params:
            person: keen
            message: '${pr_reject_message}'
            messageName: '${pr_reject_message_name}'
