id: ironcomponents_refactor
learningObjectives:
  - Refactoring a component
hints:
  - Did you import styled from styled components?
  - You can create a `StyledBanner` component that should be a styled div that uses `props.theme.dark` as the background-color
  - The styled div you created will wrap around all the previous content
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Let's do a simple refactor of our banner component. "
            delay: 2000
          - text: "For that we need to change it into a styled-component. You can see how it works in the [docs](https://styled-components.com/docs/basics#getting-started) It will be a styled div that accepts as a background color what we declared on our theme provider. [Here's](https://styled-components.com/docs/advanced#theming) how to connect with it."
            delay: 3500
          - text: ":instruction[Create a styled div for the banner that uses the dark theme as a background color. It will wrap around the existing content]. **Open a PR** when you're finished."
            delay: 1000
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_is_file_modified
                params:
                  defaultResult: true
                paramsFramework:
                  node:
                    fileName: frontend/src/Components/Home/Banner.js
                onFalseParams:
                  pr_reject_message: 'Did you create a styled component that wraps the existing Banner?'
                  pr_reject_message_name: 'missing_banner_refactor'
            then:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
            else:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: '${pr_reject_message}'
                        delay: 1000
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: '${pr_reject_message}'
                    messageName: '${pr_reject_message_name}'
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'I am seeing an error message from one of the tests in GitHub actions, please check it out and fix it.'
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: 'Looks like there are some errors. Can you try to fix it?'
        github_pr_merged:
          do:
            - actionId: finish_step
