id: ironcomponents_fixglobal
learningObjectives:
  - Changing some faulty styles
hints:
  - Remove the css styles that are removing the image and adding a background color
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: 'Oh, something is definitely not right with our application. Have you seen that background color?'
            delay: 2000
          - text: "I apparently left a couple of extra lines on the GlobalStyle file, can you remove them? Don't forget to **open a PR** so we can review it."
            delay: 3500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          if:
            conditions:
              - conditionId: github_is_file_modified
                params:
                  defaultResult: true
                paramsFramework:
                  node:
                    fileName: frontend/src/styles/GlobalStyle.js
                onFalseParams:
                  pr_reject_message: 'Did you remove the extra code from the GlobalStyle file?'
                  pr_reject_message_name: 'missing_fix'
            then:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
            else:
              do:
                - actionId: bot_message
                  params:
                    person: keen
                    messages:
                      - text: '${pr_reject_message}'
                        delay: 1000
                - actionId: github_pr_reject
                  params:
                    person: keen
                    message: '${pr_reject_message}'
                    messageName: '${pr_reject_message_name}'
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'I am seeing an error message from one of the tests in GitHub actions, please check it out and fix it.'
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: 'Looks like there are some errors. Can you try to fix it?'
        github_pr_merged:
          do:
            - actionId: finish_step
