id: iron_components_setup
learningObjectives:
  - Setting up the themes variable
hints:
  - Missing
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Now that we have the library setup we can start using some of our most common styles trough it! I'll send you a list of style properties that we use a lot troughout our application. Try to adapt them into js and into the themes object."
            delay: 2000
          - text: 'Add here a list of styles'
            delay: 3500
githubActions:
  frontend:
    capabilities:
      - jest-puppeteer
      - puppeteer
    testFile: 'theme_properties.test.js'
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: '${eventType}'
      cases:
        github_pr_opened:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
            - actionId: github_pr_comment
              params:
                person: keen
                message: "On it, I'll review the changes right away."
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
                    delay: 2000
            - actionId: github_pr_approve
              params:
                person: keen
                message: 'Nailed it! Excellent job @${user.githubuser}! You can now merge the PR.'
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: 'Make sure your fix passes all the checks, then try again please.'
                    delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: 'There seems to be something wrong with the theme. Can you double check if all the style properties are correctly applied?'
        github_pr_merged:
          do:
            - actionId: finish_step
